import * as SDK from "azure-devops-extension-sdk";
import { getClient } from "azure-devops-extension-api";
import {
  JsonPatchOperation,
  Operation,
} from "azure-devops-extension-api/WebApi";
import {
  WorkItemTrackingRestClient,
  WorkItemExpand,
} from "azure-devops-extension-api/WorkItemTracking";
import type { UserStoryContext } from "../types";

const ACCEPTANCE_CRITERIA_FIELD = "Microsoft.VSTS.Common.AcceptanceCriteria";

let cachedApiBaseUrl: string | null = null;

export async function initializeSdk(): Promise<void> {
  await SDK.init();
  await SDK.ready();
  cachedApiBaseUrl = resolveApiBaseUrl();
}

function resolveApiBaseUrl(): string {
  const config = SDK.getConfiguration();
  const fromFormConfig = config?.apiBaseUrl as string | undefined;
  if (fromFormConfig?.trim()) {
    return fromFormConfig.replace(/\/$/, "");
  }

  return "";
}

export function getApiBaseUrl(): string {
  return cachedApiBaseUrl ?? "";
}

export function setApiBaseUrl(url: string): void {
  cachedApiBaseUrl = url.replace(/\/$/, "");
}

export async function getCurrentWorkItemId(): Promise<number> {
  const config = SDK.getConfiguration();
  const id = config?.id ?? config?.workItemId;
  if (typeof id === "number") return id;
  if (typeof id === "string") return parseInt(id, 10);
  throw new Error("Unable to determine current work item ID.");
}

export async function loadUserStoryContext(
  workItemId: number
): Promise<UserStoryContext> {
  const client = getClient(WorkItemTrackingRestClient);
  const workItem = await client.getWorkItem(
    workItemId,
    undefined,
    undefined,
    undefined,
    WorkItemExpand.Fields
  );

  const fields = workItem.fields ?? {};
  return {
    id: workItemId,
    title: String(fields["System.Title"] ?? ""),
    description: String(fields["System.Description"] ?? ""),
    acceptanceCriteria: String(fields[ACCEPTANCE_CRITERIA_FIELD] ?? ""),
    areaPath: String(fields["System.AreaPath"] ?? ""),
    iterationPath: String(fields["System.IterationPath"] ?? ""),
  };
}

function buildStepsXml(
  steps: { action: string; expectedResult: string }[]
): string {
  const stepNodes = steps
    .map(
      (step, index) => `
  <step id="${index + 1}" type="ValidateStep">
    <parameterizedString isformatted="true">${escapeXml(step.action)}</parameterizedString>
    <parameterizedString isformatted="true">${escapeXml(step.expectedResult)}</parameterizedString>
    <description/>
  </step>`
    )
    .join("");

  return `<steps id="0" last="${steps.length}">${stepNodes}
</steps>`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function addField(path: string, value: string): JsonPatchOperation {
  return {
    op: Operation.Add,
    path,
    value,
    from: "",
  };
}

export async function createTestCaseWorkItem(
  userStoryId: number,
  testCase: {
    title: string;
    description: string;
    steps: { action: string; expectedResult: string }[];
  },
  context: UserStoryContext
): Promise<number> {
  const client = getClient(WorkItemTrackingRestClient);

  const patchDocument: JsonPatchOperation[] = [
    addField("/fields/System.Title", testCase.title),
    addField("/fields/System.Description", testCase.description),
    addField("/fields/System.AreaPath", context.areaPath),
    addField("/fields/System.IterationPath", context.iterationPath),
    addField(
      "/fields/Microsoft.VSTS.TCM.Steps",
      buildStepsXml(testCase.steps)
    ),
    {
      op: Operation.Add,
      path: "/relations/-",
      from: "",
      value: {
        rel: "Microsoft.VSTS.Common.TestedBy-Reverse",
        url: workItemUrl(userStoryId),
        attributes: { comment: "Generated by AI Test Case Generator" },
      },
    },
  ];

  const project = SDK.getWebContext().project?.name;
  if (!project) {
    throw new Error("Unable to determine current project.");
  }

  const created = await client.createWorkItem(
    patchDocument,
    project,
    "Test Case"
  );

  if (!created.id) {
    throw new Error(`Failed to create test case: ${testCase.title}`);
  }

  return created.id;
}

function workItemUrl(workItemId: number): string {
  const collectionUri = SDK.getWebContext().collection?.uri ?? "";
  return `${collectionUri}_apis/wit/workitems/${workItemId}`;
}
